#ifndef FLEX_LIB_COMPILER_MSVC_H__
#define FLEX_LIB_COMPILER_MSVC_H__

#define FL_MSVC_FULL_VERSION(v, r, p) v * 10000000 + r * 100000 + p
#define FL_MSVC_VERSION(v, r) FL_MSVC_FULL_VERSION(v, r, 0)

#define FL_COMPILER_MSVC _MSC_FULL_VER

#define FL_MSVS2010_VERSION FL_MSVC_FULL_VERSION(16, 0, 40219)
#define FL_MSVS2012_VERSION FL_MSVC_FULL_VERSION(17, 0, 50727)
#define FL_MSVS2013_VERSION FL_MSVC_FULL_VERSION(18, 0, 21005)
#define FL_MSVS2015_VERSION FL_MSVC_FULL_VERSION(19, 0, 23918)
#define FL_MSVC10_VERSION FL_MSVS2010_VERSION
#define FL_MSVC11_VERSION FL_MSVS2012_VERSION
#define FL_MSVC12_VERSION FL_MSVS2013_VERSION
#define FL_MSVC13_VERSION FL_MSVS2015_VERSION

#if 0
#define FL_CXX11_SUPPORT_ALIGNAS 0
#define FL_CXX11_SUPPORT_ALIGNOF 0
#define FL_CXX11_SUPPORT_ATOMIC 0
#define FL_CXX11_SUPPORT_AUTO 0
#define FL_CXX11_SUPPORT_CONSTEXPR 0
#define FL_CXX11_SUPPORT_DECLTYPE 0
#define FL_CXX11_SUPPORT_DEFAULTFUNCTIONS 0
#define FL_CXX11_SUPPORT_DELETEDFUNCTIONS 0
#define FL_CXX11_SUPPORT_DELEGATINGCTORS 0
#define FL_CXX11_SUPPORT_EXPLICITCONVS 0
#define FL_CXX11_SUPPORT_EXTENDEDFRIEND 0
#define FL_CXX11_SUPPORT_FORWARDENUMS 0
#define FL_CXX11_SUPPORT_INHERITINGCTORS 0
#define FL_CXX11_SUPPORT_INITIALIZERLISTS 0
#define FL_CXX11_SUPPORT_LAMBDAS 0
#define FL_CXX14_SUPPORT_POLYLAMBDAS 0
#define FL_CXX14_SUPPORT_LAMBDAINITINCAPTURE 0
#define FL_CXX11_SUPPORT_LOCALTYPESASTPLARGS 0
#define FL_CXX11_SUPPORT_LONGLONG 0
#define FL_CXX11_SUPPORT_INLINENAMESPACE 0
#define FL_CXX11_SUPPORT_NEWCHARTYPES 0
#define FL_CXX11_SUPPORT_AUTOFUNCTIONS 0
#define FL_CXX11_SUPPORT_NULLPTR 0
#define FL_CXX11_SUPPORT_UNICODESTRINGS 0
#define FL_CXX11_SUPPORT_RAWSTRINGS 0
#define FL_CXX11_SUPPORT_UDLITERALS 0
#define FL_CXX11_SUPPORT_RANGLEBRACKETS 0
#define FL_CXX11_SUPPORT_RVALUEREFS 0
#define FL_CXX11_SUPPORT_STATICASSERT 0
#define FL_CXX11_SUPPORT_STRONGENUMS 0
#define FL_CXX11_SUPPORT_TEMPLATEALIASES 0
#define FL_CXX11_SUPPORT_THREADLOCALSTORAGE 0
#define FL_CXX11_SUPPORT_UNRESTRICTEDUNIONS 0
#define FL_CXX11_SUPPORT_TYPETRAITS 0
#define FL_CXX11_SUPPORT_VARIADICTEMPLATES 0
#define FL_CXX11_SUPPORT_RANGEBASEDFOR 0
#define FL_CXX11_SUPPORT_OVERRIDESUPPORT 0
#define FL_CXX11_SUPPORT_ATTRIBUTES 0
#define FL_CXX11_SUPPORT_REFQUALIFIERS 0
#define FL_CXX11_SUPPORT_NONSTATICMEMBERSINIT 0
#define FL_CXX11_SUPPORT_EXTENDEDSIZEOF 0
#define FL_CXX11_SUPPORT_MAGICSTATICS 0
#endif
#define FL_CXX11_SUPPORT_ALIGNOF 0
#define FL_CXX14_SUPPORT_GENERICLAMBDAS 0
#define FL_CXX14_SUPPORT_LAMBDAINITINCAPTURE 0
#define FL_CXX11_SUPPORT_INLINENAMESPACE 0
#define FL_CXX11_SUPPORT_NEWCHARTYPES 0
#define FL_CXX11_SUPPORT_UNICODESTRINGS 0
#define FL_CXX11_SUPPORT_UDLITERALS 0
#define FL_CXX11_SUPPORT_RVALUEREFS 0
#define FL_CXX11_SUPPORT_THREADLOCALSTORAGE 0
#define FL_CXX11_SUPPORT_ATTRIBUTES 0

#if FL_COMPILER_MSVC >= FL_MSVS2010_VERSION
#define FL_CXX11_SUPPORT_AUTO 1
#define FL_CXX11_SUPPORT_DECLTYPE 1 // decltype v 1.0
#define FL_CXX11_SUPPORT_EXTENDEDFRIEND 1
#define FL_CXX11_SUPPORT_LAMBDAS 1 // lambdas v 1.0
#define FL_CXX11_SUPPORT_LOCALTYPESASTPLARGS 1
#define FL_CXX11_SUPPORT_LONGLONG 1
#define FL_CXX11_SUPPORT_AUTOFUNCTIONS 1
#define FL_CXX11_SUPPORT_NULLPTR 1
#define FL_CXX11_SUPPORT_RANGLEBRACKETS 1
#define FL_CXX11_SUPPORT_STATICASSERT 1
#define FL_CXX11_SUPPORT_STRONGENUMS 1
#define FL_CXX11_SUPPORT_TYPETRAITS 1
#   if FL_COMPILER_MSVC >= FL_MSVS2012_VERSION
#define FL_CXX11_SUPPORT_ATOMIC 1
#undef  FL_CXX11_SUPPORT_DECLTYPE
#define FL_CXX11_SUPPORT_DECLTYPE 2 // decltype v 1.1
#define FL_CXX11_SUPPORT_FORWARDENUMS 1
#undef  FL_CXX11_SUPPORT_LAMBDAS
#define FL_CXX11_SUPPORT_LAMBDAS 2 // lambdas v 1.1
#define FL_CXX11_SUPPORT_RANGEBASEDFOR 1
#define FL_CXX11_SUPPORT_OVERRIDESUPPORT 1
#       if FL_COMPILER_MSVC >= FL_MSVS2013_VERSION
#define FL_CXX11_SUPPORT_DEFAULTFUNCTIONS 1
#define FL_CXX11_SUPPORT_DELETEDFUNCTIONS 1
#define FL_CXX11_SUPPORT_DELEGATINGCTORS 1
#define FL_CXX11_SUPPORT_EXPLICITCONVS 1
#define FL_CXX11_SUPPORT_INITIALIZERLISTS 1
#define FL_CXX11_SUPPORT_RAWSTRINGS 1
#define FL_CXX11_SUPPORT_TEMPLATEALIASES 1
#define FL_CXX11_SUPPORT_VARIADICTEMPLATES 1
#define FL_CXX11_SUPPORT_NONSTATICMEMBERSINIT 1
#           if FL_COMPILER_MSVC > FL_MSVS2013_VERSION // MSVS 2013 Nov CTP and better
#define FL_CXX11_SUPPORT_ALIGNAS 1
#define FL_CXX11_SUPPORT_CONSTEXPR 1
#define FL_CXX11_SUPPORT_INHERITINGCTORS 1
#define FL_CXX11_SUPPORT_REFQUALIFIERS 1
#define FL_CXX11_SUPPORT_EXTENDEDSIZEOF 1
#define FL_CXX11_SUPPORT_MAGICSTATICS 1
#define FL_CXX11_SUPPORT_UNRESTRICTEDUNIONS 1
#           endif // FL_COMPILER_MSVC > FL_MSVS2013_VERSION
#       endif // FL_COMPILER_MSVC >= FL_MSVS2013_VERSION
#   endif // FL_COMPILER_MSVC >= FL_MSVS2012_VERSION
#else // FL_COMPILER_MSVC >= FL_MSVS2010_VERSION
#   error "Only MSVS 2010 (MSC 16.00) or better is supported"
#endif // FL_COMPILER_MSVC >= FL_MSVS2010_VERSION

#endif // FLEX_LIB_COMPILER_MSVC_H__
