#ifndef FLEX_LIB_COMPILER_GCC_H__
#define FLEX_LIB_COMPILER_GCC_H__

#if !defined(__cplusplus) || __cplusplus < 201103L
#error "-std=c++11 option should be defined for compilator command line"
#endif

#define FL_GCC_FULL_VERSION(v, r, p) (((v) << 24) + ((r) << 16) + (p))
#define FL_GCC_VERSION(v, r) FL_GCC_FULL_VERSION(v, r, 0)

#define FL_COMPILER_GCC FL_GCC_FULL_VERSION(__GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__)

#define FL_CXX14_SUPPORT_POLYLAMBDAS 0
#define FL_CXX14_SUPPORT_LAMBDAINITINCAPTURE 0

#if FL_COMPILER_GCC >= FL_GCC_VERSION(4, 5)
#define FL_CXX11_SUPPORT_ALIGNOF 1
#define FL_CXX11_SUPPORT_ATOMIC 1
#define FL_CXX11_SUPPORT_AUTO 1
#define FL_CXX11_SUPPORT_DECLTYPE 1 // decltype v 1.0, N2343
#define FL_CXX11_SUPPORT_DEFAULTFUNCTIONS 1
#define FL_CXX11_SUPPORT_DELETEDFUNCTIONS 1
#define FL_CXX11_SUPPORT_EXPLICITCONVS 1
#define FL_CXX11_SUPPORT_INITIALIZERLISTS 1
#define FL_CXX11_SUPPORT_LAMBDAS 2 // lambdas 1.1, N2927
#define FL_CXX11_SUPPORT_LOCALTYPESASTPLARGS 1
#define FL_CXX11_SUPPORT_LONGLONG 1
#define FL_CXX11_SUPPORT_INLINENAMESPACE 1
#define FL_CXX11_SUPPORT_NEWCHARTYPES 1
#define FL_CXX11_SUPPORT_AUTOFUNCTIONS 1
#define FL_CXX11_SUPPORT_UNICODESTRINGS 1
#define FL_CXX11_SUPPORT_RAWSTRINGS 1
#define FL_CXX11_SUPPORT_RANGLEBRACKETS 1
#define FL_CXX11_SUPPORT_RVALUEREFS 1
#define FL_CXX11_SUPPORT_STATICASSERT 1
#define FL_CXX11_SUPPORT_STRONGENUMS 1
#define FL_CXX11_SUPPORT_TYPETRAITS 1
#define FL_CXX11_SUPPORT_VARIADICTEMPLATES 1
#define FL_CXX11_SUPPORT_EXTENDEDSIZEOF 1
#define FL_CXX11_SUPPORT_MAGICSTATICS 1
#   if FL_COMPILER_GCC >= FL_GCC_VERSION(4, 6)
#define FL_CXX11_SUPPORT_CONSTEXPR 1
#define FL_CXX11_SUPPORT_FORWARDENUMS 1
#define FL_CXX11_SUPPORT_NULLPTR 1
#define FL_CXX11_SUPPORT_UNRESTRICTEDUNIONS 1
#define FL_CXX11_SUPPORT_RANGEBASEDFOR 1
#       if FL_COMPILER_GCC >= FL_GCC_VERSION(4, 7)
#define FL_CXX11_SUPPORT_DELEGATINGCTORS 1
#define FL_CXX11_SUPPORT_EXTENDEDFRIEND 1
#define FL_CXX11_SUPPORT_UDLITERALS 1
#define FL_CXX11_SUPPORT_TEMPLATEALIASES 1
#define FL_CXX11_SUPPORT_OVERRIDESUPPORT 1
#define FL_CXX11_SUPPORT_NONSTATICMEMBERSINIT 1
#           if FL_COMPILER_GCC >= FL_GCC_VERSION(4, 8)
#define FL_CXX11_SUPPORT_ALIGNAS 1
#undef  FL_CXX11_SUPPORT_DECLTYPE
#define FL_CXX11_SUPPORT_DECLTYPE 2 // decltype v 1.1, N3276
#define FL_CXX11_SUPPORT_INHERITINGCTORS 1
#define FL_CXX11_SUPPORT_THREADLOCALSTORAGE 1
#define FL_CXX11_SUPPORT_ATTRIBUTES 1
#               if FL_COMPILER_GCC >= FL_GCC_FULL_VERSION(4, 8, 1)
#define FL_CXX11_SUPPORT_REFQUALIFIERS 1
#                   if FL_COMPILER_GCC >= FL_GCC_VERSION(4, 9)
#                   endif // __GNUC_MINOR__ >= 9
#               endif // FL_COMPILER_GCC >= FL_GCC_FULL_VERSION(4, 8, 1)
#           endif // FL_COMPILER_GCC >= FL_GCC_VERSION(4, 8)
#       endif // FL_COMPILER_GCC >= FL_GCC_VERSION(4, 7)
#   endif // FL_COMPILER_GCC >= FL_GCC_VERSION(4, 6)
#else // FL_COMPILER_GCC >= FL_GCC_VERSION(4, 5)
#error "Only gcc 4.5 or better is supported"
#endif // // __GNUC__ == 4

#endif // FLEX_LIB_COMPILER_GCC_H__
